config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :products
  resources :carts
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :home,  only: [:index]
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :customer
    has_many :CartProducts
    has_many :products, through: :CartProduct
end

app/models/cartproduct.rb
class Cartproduct < ApplicationRecord
    
end

app/models/command.rb
class Command < ApplicationRecord
    has_many :commands
    has_many :customers, through: :commands
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :commands
    has_many :products, through: :commands
has_one :cart
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :CartProducts
    has_many :carts, through: :CartProduct
    has_one_attached :image
    validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
def index
    @products = Product.all
  end

  def new
@cart = Cart.new
  end

  def create
    @cart = Cart.new(cart_params)
  end

  private
 # Use callbacks to share common setup or constraints between actions.
 def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cart_params
    params.require(:cart).permit!
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @products = Product.all
      end
    end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :categories, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/index.html.erb
 Hello

app/views/carts/show.html.erb
Bonjour

app/views/layouts/_header.html.erb
<nav>
  <div class="container">
  </a>
      <input type="checkbox" id="showNav">
      <label for="showNav" id="toggleNav"><i class="fas fa-bars"></i></label>
      <ul>
          <li><a href="/products">Acceuil</a></li>
          <li><a href="/products">Produits</a></li>
          <% if customer_signed_in? %>
          <div >
  <%= button_to "Sign out", destroy_customer_session_path, method: :delete, id: "btn" %>
</div>
          <% else %>
          
          <li><a href="/customers/sign_up">Sign up</a></li>
          <li><a href="/customers/sign_in">Sign in</a></li>
          <% end %>
      </ul>
  </div>
</nav>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatght</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  
<%= render 'layouts/header'%>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :categories, style: "display: block" %>
    <%= form.text_field :categories %>
  </div>

  <div>
  <%= form.label :image %>
  <%= form.file_field :image %>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="container", style="margin-top: 100px;">
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Categories:</strong>
    <%= product.categories %>
  </p>

  <p>
  <% if product.image.attached? %>
  <%= image_tag(product.image, style: "height: 250px; border-radius: 15px; box-shadow: 1px 1px 12px 
  #555;")  %>
<% end %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>
<% if current_customer && current_customer.is_admin? %>
<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>
<% end %>

app/views/products/index.html.erb
<body>


<div class="block">
  <h1 class="title">Nos Chatons :</h1>
  <% if current_customer && current_customer.is_admin? %>
<%= link_to "New product", new_product_path %>
<% end %>
  <div class="product-grid">
    <%# Utilisez une boucle each pour afficher chaque produit de votre collection %>
    <% @products.each do |product| %>
      <div class="product">
    
      <div style="text-align: center;">
      <% if product.image.attached? %>
        <%= image_tag(product.image, style: "height: 250px; border-radius: 15px; box-shadow: 1px 1px 12px 
        #555;")  %>
      <% end %>
      
      <h2><%= product.name %></h2>
      <p><%= product.description %></p>
      <p>Price: <%= number_to_currency(product.price) %></p>
      <p>Categories: <%= product.categories %></p>
      <%= link_to "Show this product", product_path(product), class: "btn" %>
    </div>
      </div>
    <% end %>
  </div>
</div>
</body>

app/views/products/new.html.erb
<h1>New product</h1>
<% if current_customer && current_customer.is_admin? %>
<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>
<% end %>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
<%= link_to "Back to products", products_path %>
<% if current_customer && current_customer.is_admin? %>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= button_to "Destroy this product", @product, method: :delete %>
  <%= link_to "Back to products", products_path %>
<% end %>
 
</div>